theme: minima
title: Learn: Websites
author: a beginner who sees no end in sight
description: Will store notes from learning how to navigate website creation. For author's personally use. Not force to keep reading. 
